'use strict';
// Session-teaching: pure planner + secret/volatile screens. Hermetic — builds
// synthetic transcripts, never reads the real ~/.claude/projects.
const { test } = require('node:test');
const assert = require('node:assert');
const LS = require('./lib/learn-sessions');

// --- secret screen ----------------------------------------------------------
test('hasSecret catches common credential shapes', () => {
  assert.strictEqual(LS.hasSecret('my key is sk-ant-abcdefghijklmnopqrstuvwx'), true);
  assert.strictEqual(LS.hasSecret('GROQ_API_KEY=gsk_abcdefghijklmnopqrstuvwxyz12'), true);
  assert.strictEqual(LS.hasSecret('token ghp_abcdefghijklmnopqrstuvwxyz0123456'), true);
  assert.strictEqual(LS.hasSecret('AKIAIOSFODNN7EXAMPLE'), true);
  assert.strictEqual(LS.hasSecret('the capital of france is paris'), false);
});

test('hasSecret catches npm tokens and generic high-entropy tokens (regression)', () => {
  assert.strictEqual(LS.hasSecret('npm_faketoken1234567890abcd this ?'), true); // fake npm-shaped token
  assert.strictEqual(LS.hasSecret('is a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8 valid'), true); // 28+ mixed
  assert.strictEqual(LS.hasSecret('what is the capital of france'), false); // prose, no digit
});

test('hasSecret catches connection strings, Stripe keys, short env passwords (P0)', () => {
  assert.strictEqual(LS.hasSecret('DATABASE_URL=postgres://admin:S3cr3tPass@db.internal:5432/mydb'), true);
  assert.strictEqual(LS.hasSecret('mongodb+srv://root:toor@cluster0.mongodb.net'), true);
  assert.strictEqual(LS.hasSecret('key is sk_live_51H8xYzAbCdEfGh'), true);
  assert.strictEqual(LS.hasSecret('whsec_abcdef0123456789'), true);
  assert.strictEqual(LS.hasSecret('DB_PASSWORD=Tr0ub4dor'), true);
  assert.strictEqual(LS.hasSecret('ADMIN_PWD=x1y2z3'), true);
  assert.strictEqual(LS.hasSecret('what is the capital of france'), false);
});

test('parseTranscript drops isSidechain and isMeta turns (P0)', () => {
  const jsonl = [
    JSON.stringify({ type: 'user', isSidechain: true, message: { role: 'user', content: 'internal agent prompt' } }),
    JSON.stringify({ type: 'user', isMeta: true, message: { role: 'user', content: 'harness caveat text' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: 'what is the real question' } }),
    JSON.stringify({ type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'real answer' }] } })
  ].join('\n');
  const turns = LS.parseTranscript(jsonl);
  assert.strictEqual(turns.filter((t) => t.role === 'user').length, 1);
  assert.strictEqual(turns[0].text, 'what is the real question');
});

test('pairTurns pairs user with the FINAL assistant answer, not the preamble (P1)', () => {
  const turns = [
    { role: 'user', text: 'what is our refund window' },
    { role: 'assistant', text: 'Let me check.' },   // preamble (tool_use dropped between)
    { role: 'assistant', text: '30 days' }            // real answer
  ];
  const pairs = LS.pairTurns(turns);
  assert.strictEqual(pairs.length, 1);
  assert.strictEqual(pairs[0].answer, '30 days');
});

test('chit-chat and pricing are NOT cached as facts (P1)', () => {
  assert.strictEqual(LS.isStableFact('thanks that worked perfectly great', 'you are welcome'), false);
  assert.strictEqual(LS.isStableFact('what is the pro tier price', 'the pro tier is 49 dollars per month'), false);
  assert.strictEqual(LS.isReusablePrompt('thanks that worked'), false);
});

test('isMetaNoise filters harness/system injections', () => {
  assert.strictEqual(LS.isMetaNoise('[Request interrupted by user for tool use]'), true);
  assert.strictEqual(LS.isMetaNoise('<command-name>foo</command-name>'), true);
  assert.strictEqual(LS.isMetaNoise('Caveat: The messages below were generated by the user'), true);
  assert.strictEqual(LS.isMetaNoise('what is our refund window'), false);
});

// --- quality / volatility screen --------------------------------------------
test('isStableFact keeps short facts, rejects volatile/code/long', () => {
  assert.strictEqual(LS.isStableFact('what is the shaddai support email', 'cloudzncrownz@gmail.com'), true);
  assert.strictEqual(LS.isStableFact('what is the price of btc today', '$75,000'), false); // volatile
  assert.strictEqual(LS.isStableFact('write a function to sort', 'function sort(a){return a}'), false); // code
  assert.strictEqual(LS.isStableFact('hi', 'hello'), false); // prompt too short
  assert.strictEqual(LS.isStableFact('explain the thing in detail please', 'x'.repeat(700)), false); // too long
});

// --- transcript parsing (string + block-array content) ----------------------
test('parseTranscript + pairTurns pull user→assistant text, skip tools', () => {
  const jsonl = [
    JSON.stringify({ type: 'user', message: { role: 'user', content: 'what is our refund window' } }),
    JSON.stringify({ type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: '30 days' }] } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'noise' }] } }),
    JSON.stringify({ type: 'summary', summary: 'ignore me' })
  ].join('\n');
  const pairs = LS.pairTurns(LS.parseTranscript(jsonl));
  assert.strictEqual(pairs.length, 1);
  assert.strictEqual(pairs[0].prompt, 'what is our refund window');
  assert.strictEqual(pairs[0].answer, '30 days');
});

// --- planner: facts, recurring→skills, secret/volatile accounting -----------
test('planFromPairs: stable fact cached, secret dropped, volatile skipped', () => {
  const pairs = [
    { prompt: 'what is our refund window', answer: '30 days' },
    { prompt: 'what is the deploy key', answer: 'GITHUB_TOKEN=ghp_abcdefghijklmnopqrstuvwxyz0123456' },
    { prompt: 'what is the btc price now', answer: '$75k as of today' }
  ];
  const plan = LS.planFromPairs(pairs, { minRepeat: 3 });
  assert.strictEqual(plan.stats.secretsDropped, 1);
  assert.strictEqual(plan.facts.length, 1);
  assert.strictEqual(plan.facts[0].answer, '30 days');
});

test('planFromPairs: a prompt seen ≥ minRepeat becomes a skill, not a fact', () => {
  const pairs = [];
  for (let i = 0; i < 3; i++) pairs.push({ prompt: 'what is the mailing address', answer: '123 Main St' });
  const plan = LS.planFromPairs(pairs, { minRepeat: 3 });
  assert.strictEqual(plan.skills.length, 1);
  assert.strictEqual(plan.facts.length, 0);
  assert.ok(plan.skills[0].count >= 3);
  assert.ok(plan.skills[0].match.includes('mailing') || plan.skills[0].match.includes('address'));
});

test('planFromPairs: generated skills pass AURA validation', () => {
  const { validateSkill } = require('./lib/validate-skill');
  const pairs = [];
  for (let i = 0; i < 4; i++) pairs.push({ prompt: 'what is the office wifi password name', answer: 'shaddai-guest' });
  const plan = LS.planFromPairs(pairs, { minRepeat: 3 });
  assert.ok(plan.skills.length >= 1);
  for (const sk of plan.skills) {
    const { ok } = validateSkill({ name: sk.name, match: sk.match, action: sk.action });
    assert.strictEqual(ok, true, `generated skill invalid: ${JSON.stringify(sk)}`);
  }
});

test('isReusablePrompt rejects imperatives, keeps lookups/questions', () => {
  assert.strictEqual(LS.isReusablePrompt('keep working lets go'), false);
  assert.strictEqual(LS.isReusablePrompt('open the folder and see'), false);
  assert.strictEqual(LS.isReusablePrompt('finish building the api'), false);
  assert.strictEqual(LS.isReusablePrompt('what is our refund window'), true);
  assert.strictEqual(LS.isReusablePrompt('shaddai support email'), true);
});

test('imperative recurring command does NOT become a skill', () => {
  const pairs = [];
  for (let i = 0; i < 5; i++) pairs.push({ prompt: 'keep working', answer: 'ok continuing with the build' });
  const plan = LS.planFromPairs(pairs, { minRepeat: 3 });
  assert.strictEqual(plan.skills.length, 0);
  assert.strictEqual(plan.facts.length, 0);
});

test('skillMatchFrom drops stopwords, keeps content words', () => {
  const m = LS.skillMatchFrom('what is the support email address for shaddai');
  assert.ok(!m.split(' ').includes('what'));
  assert.ok(m.includes('support') || m.includes('email') || m.includes('address') || m.includes('shaddai'));
});
